### ISSUE TITLE
Registry is not loading dashboard

### ISSUE THREAD

**Issue by ashishtyagi10** [jhipster/jhipster-registry#172]
I am able to clone and run the project on my local, but when I am trying access dashboard it is not showing anything. 

My output in logs:

2017-08-09 22:46:58.019 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2017-08-09 22:46:58.074  INFO 21065 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : Started JHipsterRegistryApp in 12.62 seconds (JVM running for 13.08)
2017-08-09 22:46:58.079  INFO 21065 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : 
----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://localhost:8761
	External: 	http://127.0.1.1:8761
	Profile(s): 	[dev, native]
----------------------------------------------------------
2017-08-09 22:47:03.020 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2017-08-09 22:47:03.020 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2017-08-09 22:47:08.021 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2017-08-09 22:47:08.021 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2017-08-09 22:47:09.060  WARN 21065 --- [  XNIO-2 task-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-08-09 22:47:13.022 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2017-08-09 22:47:13.022 DEBUG 21065 --- [pool-4-thread-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null

but if I try to access http://localhost:8761/ 
browser does not show anything. Please help.

**Comment by ashishtyagi10** [comment]
So I tried to run $npm install on the project. I got following error. 


ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss
Module build failed: TypeError: Invalid PostCSS Plugin found: [0]
    at /home/ashish/code/abook/jhipster-registry/node_modules/postcss-load-plugins/lib/plugins.js:32:17
    at Array.forEach (native)
    at plugins (/home/ashish/code/abook/jhipster-registry/node_modules/postcss-load-plugins/lib/plugins.js:21:15)
    at /home/ashish/code/abook/jhipster-registry/node_modules/postcss-load-config/index.js:64:18
 @ ./src/main/webapp/content/scss/vendor.scss 4:14-194
 @ ./src/main/webapp/app/vendor.ts
 @ dll vendor


please help what should I do. Thanks

**Comment by ashishtyagi10** [comment]
Never mind issue has been resolved. I had to run yarn install.
