### ISSUE TITLE
mvn spring-cloud-netflix-eureka-server dependency pulls in old 2.5 servlet-api causing tomcat crash

### ISSUE THREAD

**Issue by jhulick** [jhipster/jhipster-registry#18]
The spring-cloud-netflix-eureka-server dependency pulls in an old 2.5 servlet-api jar and causes tomcat 8 to crash. Changing the **spring-cloud-netflix-eureka-server** dependency to **spring-cloud-starter-eureka** fixes this.

**Comment by pascalgrimaud** [comment]
Hello @jhulick 
Are you testing with Tomcat or Undertow ? Because with Undertow, the package.war seems broken => https://github.com/jhipster/jhipster-registry/issues/16 and we should migrate back from Undertow to Tomcat

**Comment by jhulick** [comment]
@pascalgrimaud I'm testing with embedded Tomcat and spring-boot:run. A correction is needed to my suggested fix. The proper fix is to add an exclusion to the spring-cloud-starter-eureka-server dependency, at least for startup and I haven't ran tests yet.

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-eureka-server</artifactId>
    <version>${spring-cloud.version}</version>
    <exclusions>
        <exclusion>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by pascalgrimaud** [comment]
I rebased my project, after the revert back to Tomcat and you're right!
1) `java -jar target/*.war` works now

2) `mvn` doesn't work :
```log
2016-03-06 18:23:21.772 ERROR 9898 --- [cat-startStop-1] org.apache.catalina.core.ContainerBase   : A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	... 6 common frames omitted
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.addFilter(Ljava/lang/String;Ljavax/servlet/Filter;)Ljavax/servlet/FilterRegistration$Dynamic;
	at org.springframework.boot.context.embedded.AbstractFilterRegistrationBean.onStartup(AbstractFilterRegistrationBean.java:225)
	at org.springframework.boot.context.embedded.FilterRegistrationBean.onStartup(FilterRegistrationBean.java:41)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:225)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:209)
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 6 common frames omitted
```

@jhulick : your suggested modification works. Can you propose a PR plz ?

**Comment by jhulick** [comment]
@pascalgrimaud PR has been submitted.

**Comment by pascalgrimaud** [comment]
thanks @jhulick !

**Comment by jhulick** [comment]
@pascalgrimaud glad to help! The jhipster project is awesome and spring-cloud updates make it a very interesting platform. Much thanks to you and the team

**Comment by jhulick** [comment]
The 'io.spring.gradle:dependency-management-plugin' actually seem to handle all the necessary exclusions for spring-cloud dependencies. I've testing this with maven and a converted gradle build file. I've also created a new PR #20. Please review and let me know if this works for you. It is probably the better way to handle deps rather than cherry pick.

**Comment by yinhaibo** [comment]
There is a gradle version to exclude servlet-api-2.5.jar
```
configurations {
    compile{
        exclude group:'javax.servlet', module: 'servlet-api'
    }
}
```
