### ISSUE TITLE
Can't work with git config server by ssh

### ISSUE THREAD

**Issue by yangyanqing** [jhipster/jhipster-registry#235]
##### **Overview of the issue**

```
[root@0188bdc147ee /]# java -jar jhipster-registry-3.2.4.war     --spring.profiles.active=prod,git     --spring.cloud.config.server.git.uri=git@192.168.56.30:config

        ??? ???   ??? ????????? ????????   ??????? ????????? ????????? ????????
        ??? ???   ??? ????????? ????????? ???????? ????????? ????????? ?????????
        ??? ?????????    ???    ????????? ???????     ???    ???????   ?????????
  ???   ??? ?????????    ???    ????????   ???????    ???    ???????   ????????
  ????????? ???   ??? ????????? ???       ????????    ???    ????????? ???  ????
   ???????  ???   ??? ????????? ???       ???????     ???    ????????? ???   ???

:: JHipster Registry :: Running Spring Boot 1.5.9.RELEASE ::
:: http://www.jhipster.tech ::

2018-01-23 03:05:09.148 ERROR 191 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Cannot clone or checkout repository
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:191)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:144)
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:116)
	at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40)
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:154)
	at org.springframework.cloud.config.server.environment.EnvironmentRepositoryPropertySourceLocator.locate(EnvironmentRepositoryPropertySourceLocator.java:50)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
	at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@192.168.56.30:config: UnknownHostKey: 192.168.56.30. RSA key fingerprint is c6:c6:c9:5e:9d:34:97:ff:bb:6b:03:0b:90:6a:1c:78
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:187)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:127)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:392)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:364)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:349)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:165)
	... 18 common frames omitted
Caused by: org.eclipse.jgit.errors.TransportException: git@192.168.56.30:config: UnknownHostKey: 192.168.56.30. RSA key fingerprint is c6:c6:c9:5e:9d:34:97:ff:bb:6b:03:0b:90:6a:1c:78
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 24 common frames omitted
Caused by: com.jcraft.jsch.JSchException: UnknownHostKey: 192.168.56.30. RSA key fingerprint is c6:c6:c9:5e:9d:34:97:ff:bb:6b:03:0b:90:6a:1c:78
	at com.jcraft.jsch.Session.checkHost(Session.java:805)
	at com.jcraft.jsch.Session.connect(Session.java:345)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 31 common frames omitted
```
 

##### **Motivation for or Use Case**

 - **Version**: jhipster-registry-3.2.4.war
 - **Docker**: 
    - `docker run -it --name jhipster-registry --rm centos:7.3.1611`
    - `docker cp  jhipster-registry-3.2.4.war  jhipster-registry:/ `
    - `yum install git openssh-clients java-1.8.0-openjdk`
    - `ssh-keygen <enter> ...` generate key with default parameter
    - `ssh-copy-id git@192.168.56.30` with password
    - `ssh git@192.168.56.30`   can login without any prompt. 
    - `git clone git@192.168.56.30:config` can work too
 - **Command**: 
    ```bash
    java -jar jhipster-registry-3.2.4.war  \
        --spring.profiles.active=prod,git  \
        --spring.cloud.config.server.git.uri=git@192.168.56.30:config
    ```

After the step above, exception raised. I also try the following way, but it still not worked.

1. Modify ssh config
    - /etc/ssh/ssh_config   <--- StrictHostKeyChecking no
    - ~/.ssh/config  <--- StrictHostKeyChecking no
2. Parameter in command line
    ```bash
    java -jar jhipster-registry-3.2.4.war \
        --spring.profiles.active=prod,git \
        --spring.cloud.config.server.git.ignoreLocalSshSettings=true \
        --spring.cloud.config.server.git.uri=git@192.168.56.30:config \
        --spring.cloud.config.server.git.search-paths=common \
        --spring.cloud.config.server.git.hostKeyAlgorithm=ssh-rsa \
        --spring.cloud.config.server.git.privateKey=MIIEp...PrivateKey in oneline... SzOk4= \
        --spring.cloud.config.server.git.hostKey=c6:c6:c9:5e:9d:34:97:ff:bb:6b:03:0b:90:6a:1c:78 \
        --spring.cloud.config.server.git.knownHostsFile=/root/.ssh/known_hosts \
        --spring.cloud.config.server.git.preferredAuthentications
    ```

##### **Reproduce the error**

Refer to **Motivation for or Use Case**

##### **Related issues**

- #89 not similar with my problem
- #123  amphibolous question without revolution

##### **JHipster Registry Version(s)**

jhipster-registry-3.2.4.war

##### **Browsers and Operating System**

It was not a problem with browser.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by yangyanqing** [comment]
I have made some progress, but no more idea.

```java
// /com/jcraft/jsch/0.1.54/jsch-0.1.54.jar!/com/jcraft/jsch/KnownHosts.class

public int check(String host, byte[] key) {
        int result = 1;
        if (host == null) {
            return result;
        } else {
            HostKey hk = null;

            try {
                hk = new HostKey(host, 0, key);
            } catch (JSchException var9) {
                return result;
            }

            Vector var5 = this.pool;
            synchronized(this.pool) {
                for(int i = 0; i < this.pool.size(); ++i) {
                    HostKey _hk = (HostKey)((HostKey)this.pool.elementAt(i));
                    if (_hk.isMatched(host) && _hk.type == hk.type) {
                        if (Util.array_equals(_hk.key, key)) {
                            return 0;
                        }

                        result = 2;
                    }
                }
            }

            return result == 1 && host.startsWith("[") && host.indexOf("]:") > 1 ? this.check(host.substring(1, host.indexOf("]:")), key) : result;
        }
    }
```

When debug to`if (_hk.isMatched(host) && _hk.type == hk.type) {`，_hk.isMatched(host) was True, but `_hk.type == hk.type` was False. _hk.type was 3(ECDSA256), hk.type was 2(SSHRSA).

```java
public class HostKey {
    private static final byte[][] names = new byte[][]{Util.str2byte("ssh-dss"), Util.str2byte("ssh-rsa"), Util.str2byte("ecdsa-sha2-nistp256"), Util.str2byte("ecdsa-sha2-nistp384"), Util.str2byte("ecdsa-sha2-nistp521")};
    protected static final int GUESS = 0;
    public static final int SSHDSS = 1;
    public static final int SSHRSA = 2;
    public static final int ECDSA256 = 3;
    public static final int ECDSA384 = 4;
    public static final int ECDSA521 = 5;
    ....
}
```

**Comment by yangyanqing** [comment]
I found a way to make it work. The following start with building git server:

1. Git Server
    1. CentOS 7.1.1611
    2. useradd git & passwd git
    3. su git
    4. mkdir ~/config; cd ~/config; git init --bare
2. **modify sshd config（/etc/ssh/sshd_config）**
    1. **Comment `#HostKey /etc/ssh/ssh_host_rsa_key`**

After step 2.i，jhipster-registry can work by the following command.

```bash
java -jar jhipster-registry-3.2.4.war  \
    --spring.profiles.active=prod,git  \
    --spring.cloud.config.server.git.uri=git@192.168.56.30:config
```

I don't know if this is the right solution.

**Comment by jdubois** [comment]
Isn't this because you use an IP and not a host name?

Le 23 janv. 2018 10:00 AM, "Yanqing Yang" <notifications@github.com> a
écrit :

**Comment by yangyanqing** [comment]
I'm sure the reason was not ip in url. 

The git server was base on linux ssh, and sshd support both rsa and ecdsa.  org.eclipse.jgit choose the first mode(rsa), but only recognize ecdsa in local known_hosts.

The command `ssh` and `git` could recognize the right type intelligently. So it maybe a bug of jgit ?

**Comment by PierreBesson** [comment]
@yangyanqing The reason **is** the IP in URL.
See this error : 
`Caused by: org.eclipse.jgit.errors.TransportException: git@192.168.56.30:config: UnknownHostKey: 192.168.56.30. RSA key fingerprint is c6:c6:c9:5e:9d:34:97:ff:bb:6b:03:0b:90:6a:1c:78`

Also this is because you are inside docker which uses it's own virtual networking so you can't access to your git server with the same IP as you would do normally (see https://docs.docker.com/engine/userguide/networking/ ! You might be able to use the --host option to fix this.

Also you are not using our official docker image and instead doing a strange setup by `docker cp` the registry war file. We are not supporting this exotic way of running the registry so we can't help you further.

**Comment by yangyanqing** [comment]
@PierreBesson Using docker cp just for debug, and the prompt is unknown**hostkey** not unknownhost. My first  reply improved it. Finally the problem was resolved by modify configuration of git server, parameter of war did not been changed.

After the reason being found, the official docker image can work too.

Read my reply again may be helpful. :)

Thanks!

**Comment by PierreBesson** [comment]
OK, It's still a bit strange that you were not affected by the docker networking issue (maybe it's because your git server is on the same host as the registry). As the issue was with the git server, let's keep this issue closed.

**Comment by yangyanqing** [comment]
# Final solution

modify ~/.ssh/config and append following lines

```java
Host git.xxx.com
User git
IdentityFile ~/.ssh/id_rsa
StrictHostKeyChecking no
```

**Comment by bdulac** [comment]
For Ubuntu, there might be a point with the entry registered via an SSH session in *~/.ssh/known_hosts*. 
 
[https://stackoverflow.com/a/44777270/1207019](https://stackoverflow.com/a/44777270/1207019)

The solution might be to generate the appropriate entry with the following command and append it to the file: 

`$ ssh-keyscan -t rsa example.org >> known_hosts`

**Comment by yangyanqing** [comment]
I had tried this method before, but it does not work. And I found another
way as follow.

[image: image.png]

Bérenger Dulac <notifications@github.com> 于2019年2月12日周二 下午10:18写道：
