### ISSUE TITLE
How to deal with registry timeouts issues ?

### ISSUE THREAD

**Issue by trixprod** [jhipster/jhipster-registry#336]
Hello Jhipster,

I have observed in my logs two kinds of frequent issues, i guess they are timeout related issues because the registration to the registry is correct and all my services are communicating very well. ( i retry a call when nodes are too much occupied )

Unfortunatly some of these errors are very annoying, let's see some stacks 

```
logger_name: com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient
message: Request execution error
stack_trace: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:278)
...
com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:102)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
        at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
        at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:89)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
        at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846)
        at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1399)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Here i got a read timed out while sending an Heart beat.
What is the heart beat purpose,  is the microservice sending a kind of ping to tell to the Eureka registry that it is still alive ?
How to retry on fail so ?

The second very (very) frequent of error is

```
message: It seems to be a socket read timeout exception, it will retry later. if it continues to happen and some eureka node occupied all the cpu time, you should set property 'eureka.server.peer-node-read-timeout-ms' to a bigger value
stack_trace: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:278)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:286)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:230)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
        ... 10 common frames omitted
Wrapped by: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48)
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
        at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116)
        at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:80)
        at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187)
        at java.lang.Thread.run(Thread.java:748)

```

That error is sent by the jhipster-registry server. It look like the registry cannot call the microservice ( same error that previous but in the other way i guess ).

My CPU occupation can be pretty big because of some computation, indeed.
I tried to put a high value in "peer-node-read-timeout-ms" property but i am not sure that it's very efficient as i'm not sure my property is taken into account.

How can i check current jhispter registry configuration ?

Here some of my configuration files ( some extract )
application.yml of my gateway 

```
eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: TestGateway
        instanceId: TestGateway:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        hostname: myservice.hostname.com
    server:
        peer-node-read-timeout-ms: 300000
        enable-self-preservation: false
ribbon:
    eureka:
        enabled: true
    ReadTimeout: 600000
    ConnectTimeout: 10000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 5
    OkToRetryOnAllOperations: true
    restclient:
        enabled: true
zuul: 
    sensitive-headers: Cookie,Set-Cookie #
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
        connect-timeout-millis: 50000
        socket-timeout-millis: 100000
        time-to-live: 100000
    semaphore:
        max-semaphores: 500
    retryable: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 20000

hystrix.command.default.execution.timeout.enabled: false # Just for a try, i think it's not compatible with previous timeout 
```

Like you can see i have played with some timeouts in hystrix / zuul / ribbon and set up a high value of peer-node-read-timeout-ms but still got the error.

I have also modified the Spring Cloud application.yml with peer-node-read-timeout-ms. ( the registry show that the file content is available on the Cloud ).
Tell me if i'm wrong but Spring Cloud config override each local resources application-{profile}.yml file ?

The Jhipster registry is deployed in docker compose with that environment props 

```
- SPRING_PROFILES_ACTIVE=dev
- SPRING_SECURITY_USER_PASSWORD=XXX
- JHIPSTER_REGISTRY_PASSWORD=XXX
- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
- JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
- JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
- JHIPSTER_METRICS_LOGS_ENABLED=true
- JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60

```
I'm surprised that dev is considered as "the default JHipster Registry profile". "prod" seems to be more obvious for me. But no matter i don't think it's relevant for my timeout issue.

Well, if you have some ideas it would be a pleasure to talk about that.
My searched on Google didn't drived me on propers solutions.

Regards

**Comment by vishal423** [comment]
@trixprod, can you try reverting to below defaults as recommended in production to see if that helps: 
```
eureka.instance.lease-renewal-interval-in-seconds: 30
eureka.instance.lease-expiration-duration-in-seconds: 90
```
This do have other side effects and would result into slow discovery of your services.

**Comment by trixprod** [comment]
> @trixprod, can you try reverting to below defaults as recommended in production to see if that helps:
> 
> ```
> eureka.instance.lease-renewal-interval-in-seconds: 30
> eureka.instance.lease-expiration-duration-in-seconds: 90
> ```
> This do have other side effects and would result into slow discovery of your services.

Hello, i've tested your solution.
Indeed, i have less errors in my logs but they are still present.

Also i have noticed in my jhipster registry an interesting behaviour.
When i click on the metrics of the services, i have to wait few seconds and the node is marked as down in metrics. ( not in the registry list )

I think this problem is related to the Heartbeat exception. 
The node doesn't give an answer in time and the registry metrics consider the service as down.

![node](https://user-images.githubusercontent.com/12997320/55438332-90dcdd00-55a1-11e9-95aa-7fc6ac6dce64.jpg)

**Comment by trixprod** [comment]
Update about metrics node marked down.

I have setup some memory limitation by containers. ( i have a 64Go memory server now ... )
And now my nodes are no more marked down.

Explanation is simple :
=> Docker use as much memory as possible.
=> The system turns as starvation as no more memory is available for some tasks.

Limitating global docker memory usage could be a nice thing.
Note : i'm not using clustering system. ( just docker and docker-compose ).

**Comment by vishal423** [comment]
You can configure resources (memory, cpu etc) allocation on containers to limit use. Another option could be to limit heap size

**Comment by PierreBesson** [comment]
Indeed an Eureka setup takes some memory to run properly and fine tuning. It is not a problem to have timeouts, network issues, slowness for initial registration, etc., as Eureka is designed for availability rather than consistency.

@trixpod I think your issue is not really reporting any actual bug. We could improve the docs on using/operating Eureka. I recognize it can be quite tricky but this is a huge work and the project has higher priorities right now.

Are you Ok to close this issue ?

**Comment by trixprod** [comment]
Hello @PierreBesson , the issue can be closed but i think we really need more documentation to better understand all timeouts used by Jhipster.

I know that we already have documentation on Eureka, Ribbon, but as Jhipster use all these technos i think we deserve some words about it.

**Comment by PierreBesson** [comment]
Feel free to open a PR on https://github.com/jhipster/jhipster.github.io/ either on the registry page or in the tips section.
