### ISSUE TITLE
what version of npm yarn

### ISSUE THREAD

**Issue by walshe** [jhipster/jhipster-registry#343]
##### **Overview of the issue**

don't see any ui - just blank screen, wondering what version of Node/Npm/yarn I am supposed to be using.

Even with no registered microservices or gateway I asume I should still see a UI ?

##### **Motivation for or Use Case**

want to set up microservices arch with registry, gateway and microservice

##### **JHipster Registry Version(s)**

cloned from master branch

##### **Browsers and Operating System**

mac os 10.12.6
chrome 73.0.3683.86 (Official Build) (64-bit)
- [ x]

**Comment by jdubois** [comment]
The version of Node+Yarn is automatically set up by Maven when you build, and Maven is embedded so its version is also fixed.
Please follow the guidelines: we need your version number to reproduce, and also what you did to build the app.
Please note we provide binaries and Docker images, which are all automatically built when we do a release: you should use them, and they do prove the builds work.

**Comment by walshe** [comment]
where do I check version ? I just checked out from master and did ./mnvw which started up like below.. still no UI viewable though

```
:: JHipster Registry :: Running Spring Boot 2.1.4.RELEASE ::
:: https://www.jhipster.tech ::

2019-04-06 12:54:41.727  INFO 40639 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: composite,dev,swagger
2019-04-06 12:54:43.742  WARN 40639 --- [  restartedMain] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2019-04-06 12:54:43.812  WARN 40639 --- [  restartedMain] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'hystrix.stream' contains invalid characters, please migrate to a valid format.
2019-04-06 12:54:46.072  WARN 40639 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-04-06 12:54:47.878 DEBUG 40639 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Registering CORS filter
2019-04-06 12:54:47.930  INFO 40639 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: composite
2019-04-06 12:54:47.933  INFO 40639 --- [  restartedMain] i.g.j.registry.config.WebConfigurer      : Web application fully configured
2019-04-06 12:54:48.143  INFO 40639 --- [  restartedMain] i.g.j.r.security.jwt.TokenProvider       : The JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.
2019-04-06 12:54:49.482 DEBUG 40639 --- [  restartedMain] i.g.j.r.config.AsyncConfiguration        : Creating Async Task Executor
2019-04-06 12:54:49.774  WARN 40639 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-04-06 12:54:50.534 DEBUG 40639 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
2019-04-06 12:54:50.549 DEBUG 40639 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 15 ms
2019-04-06 12:54:52.322  INFO 40639 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2019-04-06 12:54:52.322  INFO 40639 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
2019-04-06 12:54:52.334  INFO 40639 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1554569692332 with initial instances count: 0
2019-04-06 12:54:52.655  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2019-04-06 12:54:52.656  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2019-04-06 12:54:52.656  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2019-04-06 12:54:52.656  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2019-04-06 12:54:54.136 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2019-04-06 12:54:54.145 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2019-04-06 12:54:54.300  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2019-04-06 12:54:54.300  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2019-04-06 12:54:54.300  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2019-04-06 12:54:54.300  INFO 40639 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2019-04-06 12:54:54.874  INFO 40639 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : Started JHipsterRegistryApp in 15.876 seconds (JVM running for 16.828)
2019-04-06 12:54:54.882  INFO 40639 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : 
----------------------------------------------------------
	Application 'jhipster-registry' is running! Access URLs:
	Local: 		http://localhost:8761
	External: 	http://192.1xx.0.5:8761
	Profile(s): 	[composite, dev, swagger]
----------------------------------------------------------
2019-04-06 12:54:54.882  INFO 40639 --- [  restartedMain] i.g.j.registry.JHipsterRegistryApp       : 
----------------------------------------------------------
	Config Server: 	Connected to the JHipster Registry config server!
----------------------------------------------------------
2019-04-06 12:54:59.151 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2019-04-06 12:54:59.152 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2019-04-06 12:55:04.156 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2019-04-06 12:55:04.156 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2019-04-06 12:55:09.160 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2019-04-06 12:55:09.167 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null
2019-04-06 12:55:14.170 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Enter: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with argument[s] = []
2019-04-06 12:55:14.171 DEBUG 40639 --- [   scheduling-1] i.g.j.r.aop.logging.LoggingAspect        : Exit: io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes() with result = null

```

**Comment by jdubois** [comment]
The standard version number in package.json or pom.xml.

Anyway from what you write you didn't start the front-end, please look at the documentation. This depends on your version, but 'yarn start' should work.

**Comment by walshe** [comment]
from package.json:

"name": "jhipster-registry",
  "version": "4.1.1",


I just started again with ./mvnw and from anther shell I did a npm install and then yarn start:

```
AdminsMacBook-2:jhipster-registry newadmin$ yarn start
yarn run v1.15.2
$ yarn run webpack:dev
$ yarn run webpack-dev-server -- --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060 --watch-content-base
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060 --watch-content-base
Starting type checking service...
Using 1 worker with 2048MB memory limit
 10% building modules 3/3 modules 0 active[HPM] Proxy created: [ '/api',           
  '/services',
  '/management',
  '/swagger-resources',
  '/v2/api-docs',
  '/h2-console',
  '/config',
  '/auth' ]  ->  http://127.0.0.1:8761
(node:41177) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9060
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
