### ISSUE TITLE
Can not upgrade to jhipster 6.3.0 

### ISSUE THREAD

**Issue by jkoorts** [jhipster/jhipster-registry#380]
##### **Overview of the issue**

I clone a fresh copy, see its 6.0.0 beta and try to upgrade

##### **Motivation for or Use Case**

There is a major security issue with jhipster 6.2.0 and earlier

##### **Reproduce the error**

C:\testjhipster>git clone https://github.com/jhipster/jhipster-registry.git
Cloning into 'jhipster-registry'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (32/32), done.

Receiving objects: 100% (9267/9267), 5.70 MiB | 3.50 MiB/s, done.
Resolving deltas: 100% (4611/4611), done.

C:\testjhipster>jhipster --version
INFO! Using JHipster version installed globally
6.3.0

C:\testjhipster>cd jhipster-registry

C:\testjhipster\jhipster-registry>jhipster

..
..
..
  force src\main\webapp\manifest.webapp
SyntaxError: ';' expected. (2:9)
  1 | {
> 2 |   "name": "j-hipster-registry",
    |         ^
  3 |   "version": "0.0.1-SNAPSHOT",
  4 |   "description": "Description for JHipsterRegistry",
  5 |   "private": true,
    at e (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:10639:19)
    at coreFormat (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:13856:23)
    at format (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:14115:73)
    at formatWithCursor (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:14131:12)
    at C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:42399:15
    at Object.format (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:42418:12)
    at prettier.resolveConfig.then.options (C:\Users\jkoor\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-transforms.js:44:39)

##### **Browsers and Operating System**

Win 10

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is the JHipster Registry, it is not affected by this vulnerability, so there shouldn't be any issue.

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-registry/pull/392
