### ISSUE TITLE
JHipster Registry doesn't work with Google App Engine

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/jhipster-registry#400]
##### **Overview of the issue**

It seems that JHipster Registry has problems with deploying in Google app engine, which I am currently trying to solve. The error we are getting trying to do a deployment is,

```A 2019-12-11T06:36:16.841879Z {"severity": "WARNING", "message": "Entrypoint "java -Dthin.root=. -jar jhipster-registry-5.0.2.jar" requires a shell program to be the parent process. This will make the program slower to start and may cause unexpected behavior when shutting down. To avoid this, remove any occurrences of "&", "|", ";", "=" in your command."}Exception in thread "main" java.lang.reflect.InvocationTargetException 
A 2019-12-11T06:36:16.841921Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
A 2019-12-11T06:36:16.842008Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
A 2019-12-11T06:36:16.842020Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
A 2019-12-11T06:36:16.842033Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
A 2019-12-11T06:36:16.842044Z 	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140) 
A 2019-12-11T06:36:16.842056Z 	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107) 
A 2019-12-11T06:36:16.842067Z Caused by: java.lang.NoClassDefFoundError: org/springframework/core/env/Environment 
A 2019-12-11T06:36:16.842084Z 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) 
A 2019-12-11T06:36:16.843035Z 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) 
A 2019-12-11T06:36:16.843065Z 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473) 
A 2019-12-11T06:36:16.843084Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) 
A 2019-12-11T06:36:16.843163Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) 
A 2019-12-11T06:36:16.843191Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) 
A 2019-12-11T06:36:16.843208Z 	at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:193) 
A 2019-12-11T06:36:16.843223Z 	at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:140) 
A 2019-12-11T06:36:16.843349Z 	... 6 more 
A 2019-12-11T06:36:16.843507Z Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.Environment 
A 2019-12-11T06:36:16.843527Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) 
A 2019-12-11T06:36:16.843543Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) 
A 2019-12-11T06:36:16.843557Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) 
A 2019-12-11T06:36:16.843662Z 	at org.springframework.boot.loader.thin.ThinJarLauncher$ThinJarClassLoader.loadClass(ThinJarLauncher.java:481) 
A 2019-12-11T06:36:16.843737Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 
```

Feel free to assign this issue to me as I am currently investigating it. 😄 

##### **Motivation for or Use Case**

We need this for, https://github.com/jhipster/generator-jhipster/issues/10345

##### **Reproduce the error**

- Use the app engine generator (use the latest from https://github.com/jhipster/generator-jhipster/pull/10420) to generate the configuration for the jhipster-registry

- Make sure to correct the jar file name in `app.yaml` that is generated

- Deploy the registry to App Engine Standard

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/10345

https://github.com/jhipster/generator-jhipster/pull/10420

##### **Suggest a Fix**

Currently investigating. 🤔 

##### **JHipster Registry Version(s)**

5.0.2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
We need to adjust some things in order for the registry to be deployed to GAE. In the above PR, I've removed some logging (since we cannot write to the GAE filesystem) and added some sample settings so that users can deploy the registry easily by changing some minor config values. I'll add this information to the documentation as well. :smile:
