### ISSUE TITLE
Request execution error in  eureka

### ISSUE THREAD

**Issue by arjundevrana** [jhipster/jhipster-registry#421]
I am working with the default setting. But I am not able to start my project

<pre><font color="#717171">2020-01-27 20:21:52.777 </font><font color="#4E9A06"> INFO</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">com.netflix.discovery.DiscoveryClient   </font> : Force full registry fetch : false
<font color="#717171">2020-01-27 20:21:52.777 </font><font color="#4E9A06"> INFO</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">com.netflix.discovery.DiscoveryClient   </font> : Application is null : false
<font color="#717171">2020-01-27 20:21:52.777 </font><font color="#4E9A06"> INFO</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">com.netflix.discovery.DiscoveryClient   </font> : Registered Applications size is zero : true
<font color="#717171">2020-01-27 20:21:52.777 </font><font color="#4E9A06"> INFO</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">com.netflix.discovery.DiscoveryClient   </font> : Application version is -1: true
<font color="#717171">2020-01-27 20:21:52.777 </font><font color="#4E9A06"> INFO</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">com.netflix.discovery.DiscoveryClient   </font> : Getting all instance registry info from the eureka server
<font color="#717171">2020-01-27 20:21:52.852 </font><font color="#CC0000">ERROR</font> <font color="#75507B">17171</font> --- [  restartedMain] <font color="#06989A">c.n.d.s.t.d.RedirectingEurekaHttpClient </font> : Request execution error. endpoint=DefaultEndpoint{ serviceUrl=&apos;http://admin:admin@localhost:8761/eureka/}

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:194)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:165)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965)
	at com.netflix.discovery.DiscoveryClient.&lt;init&gt;(DiscoveryClient.java:414)
	at com.netflix.discovery.DiscoveryClient.&lt;init&gt;(DiscoveryClient.java:269)
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient.&lt;init&gt;(CloudEurekaClient.java:67)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:330)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$7febc219.CGLIB$eurekaClient$0(&lt;generated&gt;)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$7febc219$$FastClassBySpringCGLIB$$a1a5d2c5.invoke(&lt;generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$7febc219.eurekaClient(&lt;generated&gt;)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)</pre>

**Comment by juliensadaoui** [comment]
As you give no information I can't help you.

Tickets must follow our [Guidelines](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md#-submission-guidelines). 
For bug issue you can use this [template](https://github.com/jhipster/jhipster-registry/issues/new).
