### ISSUE TITLE
Not able to connect to jhipster-registry

### ISSUE THREAD

**Issue by mrsimple1982** [jhipster/jhipster-registry#441]
##### **Overview of the issue**
I am trying to run and test Jhipster microservices application(1 gateway and 1 microservice) and jhispter registry seperately on different containers. When i run these 2 containers seperately the gateway and the microservice application fail to connect. 

When i try to run these application in docker-compose file, all works fine. How can i make them work separately as i need to deploy these containers separately in production. 

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:148)
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locateCollection(ConfigServicePropertySourceLocator.java:163)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$6c2585bb.locateCollection(<generated>)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at com.ils.financialservice.FinancialserviceApp.main(FinancialserviceApp.java:63)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://jhipster-registry:8761/config/productservice/prod/master": jhipster-registry; nested exception is java.net.UnknownHostException: jhipster-registry
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:748)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:264)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:107)
        ... 21 common frames omitted
##### **Motivation for or Use Case**
I want to run the application containers separately on cloud provider managed container service(AWS) 

##### **Reproduce the error**
Create JHipster Gateway and Jhipster Microservice application. Build the application using 
./mvnw -ntp -Pprod verify jib:dockerBuild command. 

Now run jhipster registry using the yml file jhipster-registry.yml 
Run containes for JHipster Gateway and  Jhipster Microservice application.
Both the containers fail to register on the Jhipster Registry with above mentioned error.

##### **JHipster Registry Version(s)**

I am using jhipster-registry:v6.2.0

##### **Browsers and Operating System**

I have tried on both Windows 10 and Ubuntu 18.04
THe problem occurs on all browsers

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by juliensadaoui** [comment]
This behaviour is correct, it is not an issue with the JHipster Registry. To understand your problem, you need to know the concept of Docker Networking and how the applications can access each other, using internal network created by docker.

There are several network drivers: Bridge, Host, None, ...
The Bridge driver is a private default internal network created by docker on the host. This network is usually used when your applications run in standalone containers that need to communicate. So, all containers get an internal IP address and these containers can access each other, using this internal IP.

In your case, you try to communicate with the JHipster Registry using the service name **jhipster-registry**. This service name works only when you deployed your containers using Docker Compose. When your applications run in standalone containers, each container get an internal IP address and you should use this address to communicate with other container.
